fatal error: concurrent map iteration and map write
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
(cherry picked from commit 5a3a9baec96cb674406eeecf93da6e5e1fb201d6)
Signed-off-by: Derek McGowan <derek@mcg.dev>