add WithAppendAdditionalGroups helper
Signed-off-by: Ye Sijun <junnplus@gmail.com>
(cherry picked from commit 5bf705255df9d2ad3aec123e60bd149d10df7c57)

Cherry-pick was clean but had a compilation error:
> oci/spec_opts.go:794:26: undefined: runtime
Manually modified to resolve the compilation error.

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>