Fix lint failures
```
oci/spec_opts.go:581: File is not `gofmt`-ed with `-s` (gofmt)
                // and the OCI Runtime Spec has no definition about the max UID,
                // the runc implementation is known to require the UID to be <= MaxInt32.
                //
                // containerd follows runc's limitation here.
                //
                // In future we may relax this limitation to allow MaxUint32 - 2,
                // or, amend the OCI Runtime Spec to codify the implementation limitation.
Error: pkg/cri/streaming/internal/wsstream/conn.go:72:1: Duplicate words (be) found (dupword)
// be valid) and data written by the server to the client is base64 encoded.
^
Error: services/introspection/local.go:98:59: printf: non-constant format string in call to github.com/containerd/errdefs.ToGRPCf (govet)
		return nil, errdefs.ToGRPCf(errdefs.ErrInvalidArgument, err.Error())
		                                                        ^
Error: services/content/contentserver/contentserver.go:134:52: printf: non-constant format string in call to google.golang.org/grpc/status.Errorf (govet)
		return nil, status.Errorf(codes.InvalidArgument, err.Error())
		                                                 ^
Error: filters/parser.go:211:27: printf: non-constant format string in call to (*github.com/containerd/containerd/filters.parser).mkerr (govet)
		return "", p.mkerr(pos, p.scanner.err)
		                        ^
Error: filters/parser.go:232:26: printf: non-constant format string in call to (*github.com/containerd/containerd/filters.parser).mkerr (govet)
		return 0, p.mkerr(pos, p.scanner.err)
		                       ^
Error: filters/parser.go:247:27: printf: non-constant format string in call to (*github.com/containerd/containerd/filters.parser).mkerr (govet)
		return "", p.mkerr(pos, p.scanner.err)
		                        ^
Error: remotes/docker/fetcher_test.go:149:31: printf: non-constant format string in call to fmt.Errorf (govet)
			mockedErr:      fmt.Errorf(http.StatusText(http.StatusRequestTimeout)),
			                           ^
Error: remotes/docker/fetcher_test.go:157:31: printf: non-constant format string in call to fmt.Errorf (govet)
			mockedErr:      fmt.Errorf(http.StatusText(http.StatusTooManyRequests)),
			                           ^
Error: cio/io_test.go:46:5: SA4032: due to the file's build constraints, runtime.GOOS will never equal "windows" (staticcheck)
	if runtime.GOOS == "windows" {
	   ^
Error: cio/io_test.go:79:5: SA4032: due to the file's build constraints, runtime.GOOS will never equal "windows" (staticcheck)
	if runtime.GOOS == "windows" {
	   ^
Error: archive/tar.go:335:2: directive `//nolint:staticcheck // TypeRegA is deprecated but we may still receive an external tar with TypeRegA` is unused for linter "staticcheck" (nolintlint)
	//nolint:staticcheck // TypeRegA is deprecated but we may still receive an external tar with TypeRegA
	^
Error: images/archive/importer.go:97:3: directive `//nolint:staticcheck // TypeRegA is deprecated but we may still receive an external tar with TypeRegA` is unused for linter "staticcheck" (nolintlint)
		//nolint:staticcheck // TypeRegA is deprecated but we may still receive an external tar with TypeRegA
		^
Error: pkg/cri/server/image_pull.go:335:38: directive `//nolint:staticcheck` is unused for linter "staticcheck" (nolintlint)
		tlsConfig.BuildNameToCertificate() //nolint:staticcheck
```

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>